pushing to aws ecr

diff --git a/.github/workflows/ben10.yml b/.github/workflows/ben10.yml
--- a/.github/workflows/ben10.yml
+++ b/.github/workflows/ben10.yml
@@ -4,7 +4,6 @@ on:
     branches:
       - taiwo/ben10
 
-
 jobs:
   build:
     name: Build Ben10 Image
@@ -29,9 +28,9 @@ jobs:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         ECR_REPOSITORY: ben10-account
       run: |
-        echo "$ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_RUN_NUMBER}"
-        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_RUN_NUMBER} .
-        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_RUN_NUMBER}
+        echo "$ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_RUN_NUMBER"  # Corrected tag format
+        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_RUN_NUMBER .
+        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_RUN_NUMBER
 
   pilot-deploy:
     name: Deploy Ben10 to dev
@@ -41,7 +40,7 @@ jobs:
       ECR_REPOSITORY: ben10-account
       DIRECTORY: ben10
       COMPOSE: compose.yml
-      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+      ECR_REGISTRY: ${{vars.ECR_REGISTRY}}
     steps:
     - name: ssh login to Ben10 EC2 Instance
       uses: appleboy/ssh-action@v1.0.3
@@ -52,19 +51,12 @@ jobs:
         port: ${{ secrets.PORT }}
         envs: GITHUB_TRIGGERING_ACTOR,GITHUB_RUN_NUMBER,ECR_REGISTRY,ECR_REPOSITORY,DIRECTORY,COMPOSE
         script: |
-          echo "Environment Variables:"
-          echo "GITHUB_TRIGGERING_ACTOR: $GITHUB_TRIGGERING_ACTOR"
-          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
-          echo "ECR_REGISTRY: $ECR_REGISTRY"
-          echo "ECR_REPOSITORY: $ECR_REPOSITORY"
-          echo "DIRECTORY: $DIRECTORY"
-          echo "COMPOSE: $COMPOSE"
-          echo  "$GITHUB_TRIGGERING_ACTOR -Deployment Initiated- \nPulling build artifact $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_RUN_NUMBER}"
+          echo  "$GITHUB_TRIGGERING_ACTOR -Deployment Initiated- \nPulling build artifact $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_RUN_NUMBER"
           cd $DIRECTORY && yq -y -i '.services.web.image = "${ECR_REGISTRY}/${ECR_REPOSITORY}:${GITHUB_RUN_NUMBER}"' $COMPOSE && \
           docker compose up --build --force-recreate -d
           if [[ $? == 0 ]]; then
             echo "Deployment Successful!!!"
-            else
-              echo "Error!!!!! can not recreate service update"
-              exit 1
+          else
+            echo "Error!!!!! can not recreate service update"
+            exit 1
           fi
