Deploy Ben10 to Amazon ECR

diff --git a/.github/workflows/ben10.yml b/.github/workflows/ben10.yml
--- a/.github/workflows/ben10.yml
+++ b/.github/workflows/ben10.yml
@@ -1,28 +1,64 @@
-name: CI/CD Pipeline and AWS Balancer
+name: Deploy Ben10 future Microservice
 on:
   push:
     branches:
       - taiwo/ben10
+
+
 jobs:
-  deploy:
+  build:
+    name: Build Ben10 Image
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+    - name: Check out code
+      uses: actions/checkout@v2
 
-      - name: Set Workflow ID as Environment Variable
-        run: echo "WORKFLOW_ID=${{ github.run_id }}" >> $GITHUB_ENV
+    - name: Configure AWS credentials
+      uses: aws-actions/configure-aws-credentials@v1
+      with:
+        aws-access-key-id: ${{ secrets.TEEWAI_AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.TEEWAI_AWS_SECRET_ACCESS_KEY }}
+        aws-region: us-east-1
 
-      - name: Login to the EC2
-        uses: appleboy/ssh-action@v1.0.3
-        with:
-            host: ${{ secrets.TEEWAI_HOST }}
-            username: ${{ secrets.TEEWAI_USERNAME }}
-            key: ${{ secrets.TEEWAI_KEY }}
-            port: ${{ secrets.PORT }}
-            script: |        
-              echo "WORKFLOW_ID=${{ github.run_id }}" | sudo tee -a /etc/environment
-              source /etc/environment
-              cd ben10
-              git pull origin taiwo/ben10
-              docker compose up --detach --build
+    - name: Login to Ben10 ECR
+      id: login-ecr
+      uses: aws-actions/amazon-ecr-login@v1
+
+    - name: Build, tag, and push image to Amazon ECR
+      env:
+        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+        ECR_REPOSITORY: ben10-account
+      run: |
+        echo "$ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_RUN_NUMBER}"
+        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_RUN_NUMBER} .
+        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_RUN_NUMBER}
+
+  pilot-deploy:
+    name: Deploy Ben10 to dev
+    runs-on: ubuntu-latest
+    needs: build
+    if: github.ref == 'refs/heads/taiwo/ben10'
+    env:
+      ECR_REPOSITORY: ben10-account
+      DIRECTORY: account
+      COMPOSE: compose.yml
+      ECR_REGISTRY: ${{vars.ECR_REGISTRY}}
+    steps:
+    - name: ssh login to Primus EC2 Instance
+      uses: appleboy/ssh-action@v1.0.0
+      with:
+        host: ${{ secrets.TEEWAI_HOST }}
+        username: ${{ secrets.TEEWAI_USERNAME }}
+        key: ${{ secrets.TEEWAI_KEY }}
+        port: ${{ secrets.PORT }}
+        envs: GITHUB_TRIGGERING_ACTOR,GITHUB_RUN_NUMBER,ECR_REGISTRY,ECR_REPOSITORY,DIRECTORY,COMPOSE
+        script: |
+          echo  "$GITHUB_TRIGGERING_ACTOR -Deployment Initiated- \nPulling build artifact $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_RUN_NUMBER}"
+          cd $DIRECTORY && yq '.services.account-service.image = "${ECR_REGISTRY}/${ECR_REPOSITORY}:${GITHUB_RUN_NUMBER}"' -i  $COMPOSE && \
+          docker-compose up --build --force-recreate -d
+          if [[ $? == 0 ]]; then
+            echo "Deployment Successful!!!"
+            else
+              echo "Error!!!!! can not recreate service update"
+              exit 1
+          fi
