pushing to aws ecr

diff --git a/.github/workflows/ben10.yml b/.github/workflows/ben10.yml
--- a/.github/workflows/ben10.yml
+++ b/.github/workflows/ben10.yml
@@ -4,6 +4,7 @@ on:
     branches:
       - taiwo/ben10
 
+
 jobs:
   build:
     name: Build Ben10 Image
@@ -28,11 +29,18 @@ jobs:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         ECR_REPOSITORY: ben10-account
       run: |
-        echo "$ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_RUN_NUMBER"  # Corrected tag format
-        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_RUN_NUMBER .
-        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_RUN_NUMBER
+        echo "$ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_RUN_NUMBER}"
+        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_RUN_NUMBER} .
+        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_RUN_NUMBER}
+        echo "$ECR_REGISTRY" > ecr_registry.txt
+    - name: Upload ECR Registry
+      uses: actions/upload-artifact@v2
+      with:
+        name: ecr-registry
+        path: ecr_registry.txt
 
-  pilot-deploy:
+
+   pilot-deploy:
     name: Deploy Ben10 to dev
     runs-on: ubuntu-latest
     needs: build
@@ -40,7 +48,18 @@ jobs:
       ECR_REPOSITORY: ben10-account
       DIRECTORY: ben10
       COMPOSE: compose.yml
-      ECR_REGISTRY: ${{vars.ECR_REGISTRY}}
+      
+    steps:
+    - name: Download ECR Registry
+      uses: actions/download-artifact@v2
+      with:
+        name: ecr-registry
+        path: .
+    - name: Read ECR Registry
+      run: |
+        ECR_REGISTRY=$(cat ecr_registry.txt)
+        echo "ECR_REGISTRY=$ECR_REGISTRY" >> $GITHUB_ENV
+        
     steps:
     - name: ssh login to Ben10 EC2 Instance
       uses: appleboy/ssh-action@v1.0.3
@@ -51,12 +70,19 @@ jobs:
         port: ${{ secrets.PORT }}
         envs: GITHUB_TRIGGERING_ACTOR,GITHUB_RUN_NUMBER,ECR_REGISTRY,ECR_REPOSITORY,DIRECTORY,COMPOSE
         script: |
-          echo  "$GITHUB_TRIGGERING_ACTOR -Deployment Initiated- \nPulling build artifact $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_RUN_NUMBER"
+          echo "Environment Variables:"
+          echo "GITHUB_TRIGGERING_ACTOR: $GITHUB_TRIGGERING_ACTOR"
+          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
+          echo "ECR_REGISTRY: $ECR_REGISTRY"
+          echo "ECR_REPOSITORY: $ECR_REPOSITORY"
+          echo "DIRECTORY: $DIRECTORY"
+          echo "COMPOSE: $COMPOSE"
+          echo  "$GITHUB_TRIGGERING_ACTOR -Deployment Initiated- \nPulling build artifact $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_RUN_NUMBER}"
           cd $DIRECTORY && yq -y -i '.services.web.image = "${ECR_REGISTRY}/${ECR_REPOSITORY}:${GITHUB_RUN_NUMBER}"' $COMPOSE && \
           docker compose up --build --force-recreate -d
           if [[ $? == 0 ]]; then
             echo "Deployment Successful!!!"
-          else
-            echo "Error!!!!! can not recreate service update"
-            exit 1
+            else
+              echo "Error!!!!! can not recreate service update"
+              exit 1
           fi
